### PR TITLE
Exclude site packages from Travis build

### LINKED ISSUE #24: Site packages should be excluded from test coverage
Since `site packages` are not part of our implementation, they should not be considered when determining our applications code coverage. Including them gives us a false test coverage percentage.

Considering excluding from the test script in the travis.yml file.

Below is the link showing how the site packages are negatively affecting test coverage.
[https://coveralls.io/github/azaria-dedmon/covid-19?branch=coveralls](https://coveralls.io/github/azaria-dedmon/covid-19?branch=coveralls)

### PR DESCRIPTION
**Pull request by azaria-dedmon**
**What does this PR do?**

- This PR fixes #24 

**Description of Task to be completed.**

- Exclude `site packages` from test coverage.

### CODE REVIEW

**Comment by azaria-dedmon** [comment]
For some reason, the code coverage test is no longer being included in the **checks**. Does this indicate that something is incorrect with the travis file? Typically there are **4** checks instead of **3**.

**Comment by alexkayabula** [comment]
> For some reason, the code coverage test is no longer being included in the **checks**. Does this indicate that something is incorrect with the travis file? Typically there are **4** checks instead of **3**.

**Comment by alexkayabula** [comment]
No, that does not imply that the travis file is incorrect. But the changes you made don't fix the issue. I have refactored and made the required changes. Please review.

**Comment by alexkayabula** [comment]
@azaria-dedmon also note the changes I have made in the PR description.

**Review by alexkayabula — APPROVED** [review]
LGTM.

**Pull request merged**
