### PR TITLE
Fix failing CI/CD build when application database is configured

### LINKED ISSUE #30: Failing CI/CD build when application database is configured
When the application database is configured, the build fails

### PR DESCRIPTION
**Pull request by alexkayabula**
### What does this PR do?
- This PR fixes the CI/CD build when application database is configured.
- Fixes #30 

### Tasks
- [x] Restructure and improve project structure.
- [x] Configure application environments i.e Production, Testing, Development.
- [x] Configure `prospector.yml` to exclude anomalous pycodestyles.

### CODE REVIEW

**Comment by alexkayabula** [comment]
@azaria-dedmon please look through this PR and ask any questions or give any feedback if any.

**Comment by azaria-dedmon** [comment]
@alexkayabula Everything looks greats but I would like further explanation on why we're using `app/__init__.py` and adding new information to that file instead of `app.py`. I'm only familiar with using app.py

**Comment by alexkayabula** [comment]
> @alexkayabula Everything looks greats but I would like further explanation on why we're using `app/__init__.py` and adding new information to that file instead of `app.py`. I'm only familiar with using app.py

Putting the Flask application object in the `__init__.py` file allows each module to import it safely and the `__name__` variable to resolve to the correct package.

**Comment by alexkayabula** [comment]
LGTM

**Pull request merged**
