### PR TITLE
Update navbar text and functionality

### PR DESCRIPTION
**Pull request by azaria-dedmon**
**What does this PR do?**

This PR updates the following functionality to the navbar:
- `Home` link 
- `Testing Site Reviews` link
- Position the `search bar` as well as `search` button
- Navbar text 

**Description of task to be completed.**

- Add `Home` link to the navbar.
- Add `Testing Site Reviews` link to the `edit user` page as well as `map` page
-  Position the `search bar` as well as `search` button
- Increase `font-size` and `font-weight` of navbar text

**How should this be manually tested?**

This does not have to be tested.

### CODE REVIEW

**Comment by alexkayabula** [comment]
@azaria-dedmon since you are working on the navbar please fix the issues below.
1. Ensure that the `search username` field and Search button are on the same level with other navbar text i.e Home, Test Site reviews etc.
2. Increase the `font size` of all navbar text and make it bold.

**Comment by azaria-dedmon** [comment]
> @azaria-dedmon since you are working on the navbar please fix the issues below.
> 
> 1. Ensure that the `search username` field and Search button are on the same level with other navbar text i.e Home, Test Site reviews etc.
> 2. Increase the `font size` of all navbar text and make it bold.

I was going to make adjustments to the "search username" field and search button in a separate PR. Should I be including those updates in this PR?

**Comment by alexkayabula** [comment]
Yeah...don't forget to edit the PR title and description to reflect the changes being made.

**Comment by azaria-dedmon** [comment]
> Yeah...don't forget to edit the PR title and description to reflect the changes being made.

I would also like to add "Testing Site Reviews" link to the navbar for the `edit user` page as well as for the `map `page. Would it be okay to also add that change to this PR as well?

**Comment by alexkayabula** [comment]
Yeah it is....make sure everything we need to change in the navbar is fixed in this PR.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
@azaria-dedmon the search field and search button are still not on the same level as other items in the navbar. Please address this issue.

**Review by alexkayabula — APPROVED** [review]
Thank you.

**Pull request merged**
